In [ ]:
import numpy as np

# Array creation functions


We are going to discuss the follwoing question.
1. array()
2. asarray()
3. arange()
4. ones()
5. zeros()
6. empty()
7. eye()
8. full()

## array()
array() help us to create the numpy array in python. We can create array from list, tuple, list of lists, tuple of tuples.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

# create an array from a tuple
arr = np.array((6, 7, 8, 9, 10))
print(arr)

# create an array from a list of lists
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

# create an array from a tuple of tuples
arr = np.array(((1, 2, 3), (4, 5, 6)))
print(arr)

[1 2 3 4 5]
[ 6  7  8  9 10]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


## asarray()
as array help us to convert the any other data type into array.

In [ ]:
# array()
# create a list
list = [1, 2, 3, 4, 5]

# convert the list to an array
arr = np.asarray(list)
arr

array([1, 2, 3, 4, 5])

## arange()
The arange() function creates a Numpy array with a range of values specified by the start, stop, and step parameters. The start and stop values are inclusive and exclusive, respectively, and the step parameter determines the interval between the values in the array.

In [ ]:
# create an array with values from 0 to 9, inclusive
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# create an array with values from 0 to 9, exclusive
arr = np.arange(10, 20)
print(arr)

[10 11 12 13 14 15 16 17 18 19]


In [ ]:
# create an array with values from 0 to 9, with a step size of 2
arr = np.arange(0, 10, 2)
print(arr)


[0 2 4 6 8]


In [ ]:
# create an array with values from 9 to 0, with a step size of -1
arr = np.arange(9, -1, -1)
print(arr)


[9 8 7 6 5 4 3 2 1 0]


In [ ]:
# create an array with values from 0 to 1, with a step size of 0.1
arr = np.arange(0, 1, 0.1)
print(arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


## ones() & zeros() & empty()
he ones() function creates a Numpy array with a specified shape and data type, filled with ones. In the same manner, zeros() fill the values with zeros. Empty() create the specified shape only without filling the numbers. Here is the example of both.

In [ ]:
# create a 1-dimensional array with 5 ones
arr = np.ones(5)
print(arr)

# create a 1-dimensional array with 5 zeros
arr = np.zeros(5)
print(arr)

# create a 1-dimensional array with 5 empty
arr = np.empty(5)
print(arr)


# create a 2-dimensional array with 3 rows and 4 columns of ones
arr = np.ones((3, 4))
print(arr)

# create a 2-dimensional array with 3 rows and 4 columns of zeros
arr = np.zeros((3, 4))
print(arr)

[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In empty(), The elements of the array will contain whatever values were in the memory before the array was created.

This function is often used to create an array with a certain shape and data type, to be later populated with more meaningful data. It is generally faster than creating an array with the ones() or zeros() function, as it does not need to initialize the elements to a specific value. However, the elements of the array may contain garbage values, so it is important to be aware of this

# eye()
eye() function help us to create the identity matrix in python. You can also specify the location of diagonal as well.

In [ ]:
# create a 4x4 identity matrix
arr = np.eye(4)
print(arr)

# create a 5x5 identity matrix with a non-zero diagonal
arr = np.eye(5, k=-3)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]


In [ ]:
# create a 2x3 identity matrix with a non-zero diagonal
arr = np.eye(2, 3, k=1)
print(arr)

[[0. 1. 0.]
 [0. 0. 1.]]


## full()
The full() function creates a Numpy array with a specified shape and data type, filled with a single value. Shape can be of anytype.

In [ ]:
# create a 1-dimensional array with 5 elements
arr = np.full(3, 5)
print(arr)

# create a 2-dimensional array with 3 rows and 6 columns
arr = np.full((3, 6), 2)
print(arr)


[5 5 5]
[[2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]]


In [ ]:
arr = np.full(3, 5, dtype=np.float64)
print(arr)

[5. 5. 5.]


# Array Manipulation



1. np.reshape: reshapes an array into a specified shape
2. np.ndarray.flatten: flattens an array into a single dimension
3. np.transpose: transposes an array by swapping its axes
4. np.concatenate: concatenates two or more arrays along a specified axis
5. np.split: splits an array into multiple subarrays along a specified axis
6. np.vsplit: splits an array vertically (row-wise)
7. np.hsplit: splits an array horizontally (column-wise)
8. np.stack: stacks arrays along a new axis
9. np.vstack: stacks arrays vertically (row-wise)
10. np.hstack: stacks arrays horizontally (column-wise)
11. np.column_stack: stacks 1D arrays as columns in a 2D array
12. np.dstack: stacks arrays along a new third axis (depth)

In [ ]:
# create a 1-dimensional array
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)

# reshape the array into a 2-dimensional array with 5 rows and 2 columns
arr2 = np.reshape(arr, (5, 2))
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
# flatten the array into a 1-dimensional array
arr3 = np.ndarray.flatten(arr2)
print(arr3)
arr5 = np.ndarray.flatten(arr2, order='F')
arr5

[0 1 2 3 4 5 6 7 8 9]


array([0, 2, 4, 6, 8, 1, 3, 5, 7, 9])

In [ ]:
# transpose the array
arr4 = np.transpose(arr2)
print(arr4)

[[0 2 4 6 8]
 [1 3 5 7 9]]


In [ ]:
# create a second array to concatenate with the first
arr5 = np.array([10, 11, 12, 13, 14, 15])

# concatenate the two arrays along the first axis
arr6 = np.concatenate((arr, arr5), axis=0)
print(arr6)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
# split the concatenated array into three equal-sized subarrays
arr7 = np.split(arr6, 2)
print(arr7)


[array([0, 1, 2, 3, 4, 5, 6, 7]), array([ 8,  9, 10, 11, 12, 13, 14, 15])]


In [ ]:
# create a 2-dimensional array with 4 rows and 4 columns
arr = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]])
print(arr)

# split the array vertically into two arrays
arr2, arr3 = np.vsplit(arr, 2)
print(arr2)
print(arr3)

# split the array horizentally into two arrays
arr4, arr5 = np.hsplit(arr, 2)
print(arr4)
print(arr5)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [ ]:
# stack the two arrays vertically
arr10 = np.vstack((arr2, arr3))
print(arr10)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
# stack the two arrays horizontally
arr11 = np.hstack((arr4, arr5))
print(arr11)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
# stack the two arrays along the second axis
arr12 = np.column_stack((arr, arr5))
print(arr12)

[[ 0  1  2  3  2  3]
 [ 4  5  6  7  6  7]
 [ 8  9 10 11 10 11]
 [12 13 14 15 14 15]]


## Mathematics and statistical Functions
### MAthematics
1. np.abs: calculates the absolute value of an array
2. np.add: adds two arrays element-wise
3. np.subtract: subtracts one array from another element-wise
4. np.multiply: multiplies two arrays element-wise
5. np.divide: divides one array by another element-wise
6. np.exp: calculates the exponent of an array
7. np.log: calculates the natural logarithm of an array
8. np.sqrt: calculates the square root of an array
9. np.power: raises an array to a specified power
10. np.maximum: calculates the element-wise maximum of two arrays
11. np.minimum: calculates the element-wise minimum of two arrays
12. np.mod: calculates the element-wise remainder of two arrays
13. np.around: rounds the elements of an array to the nearest integer
14. np.floor: rounds the elements of an array down to the nearest integer
15. np.ceil: rounds the elements of an array up to the nearest integer

In [ ]:
data = np.array([[-1.2, 2.4, 3.6], [4.1, 5.7, 6.2]])

# absolute value
abs_data = np.abs(data)
print("Absolute value:\n", abs_data)

# element-wise addition
add_data = np.add(data, 2)
print("\nAddition:\n", add_data)

# element-wise subtraction
sub_data = np.subtract(data, 2)
print("\nSubtraction:\n", sub_data)

# element-wise multiplication
mul_data = np.multiply(data, 2)
print("\nMultiplication:\n", mul_data)

# element-wise division
div_data = np.divide(data, 2)
print("\nDivision:\n", div_data)

# exponentiation
exp_data = np.exp(data)
print("\nExponentiation:\n", exp_data)

# natural logarithm
log_data = np.log(data)
print("\nNatural logarithm:\n", log_data)

# square root
sqrt_data = np.sqrt(data)
print("\nSquare root:\n", sqrt_data)

# power
pow_data = np.power(data, 2)
print("\nPower:\n", pow_data)

# element-wise maximum
max_data = np.maximum(data, 2)
print("\nElement-wise maximum:\n", max_data)

# element-wise minimum
min_data = np.minimum(data, 2)
print("\nElement-wise minimum:\n", min_data)

# element-wise remainder
mod_data = np.mod(data, 2)
print("\nElement-wise remainder:\n", mod_data)

# rounding
round_data = np.around(data)
print("\nRounding:\n", round_data)
floor_data = np.floor(data)
print("\nFloor:\n", floor_data)
ceil_data = np.ceil(data)
print("\nCeiling:\n", ceil_data)

Absolute value:
 [[1.2 2.4 3.6]
 [4.1 5.7 6.2]]

Addition:
 [[0.8 4.4 5.6]
 [6.1 7.7 8.2]]

Subtraction:
 [[-3.2  0.4  1.6]
 [ 2.1  3.7  4.2]]

Multiplication:
 [[-2.4  4.8  7.2]
 [ 8.2 11.4 12.4]]

Division:
 [[-0.6   1.2   1.8 ]
 [ 2.05  2.85  3.1 ]]

Exponentiation:
 [[3.01194212e-01 1.10231764e+01 3.65982344e+01]
 [6.03402876e+01 2.98867401e+02 4.92749041e+02]]

Natural logarithm:
 [[       nan 0.87546874 1.28093385]
 [1.41098697 1.74046617 1.82454929]]

Square root:
 [[       nan 1.54919334 1.8973666 ]
 [2.02484567 2.38746728 2.48997992]]

Power:
 [[ 1.44  5.76 12.96]
 [16.81 32.49 38.44]]

Element-wise maximum:
 [[2.  2.4 3.6]
 [4.1 5.7 6.2]]

Element-wise minimum:
 [[-1.2  2.   2. ]
 [ 2.   2.   2. ]]

Element-wise remainder:
 [[0.8 0.4 1.6]
 [0.1 1.7 0.2]]

Rounding:
 [[-1.  2.  4.]
 [ 4.  6.  6.]]

Floor:
 [[-2.  2.  3.]
 [ 4.  5.  6.]]

Ceiling:
 [[-1.  3.  4.]
 [ 5.  6.  7.]]


<ipython-input-3-c501eb71cf7f>:28: RuntimeWarning: invalid value encountered in log
  log_data = np.log(data)
<ipython-input-3-c501eb71cf7f>:32: RuntimeWarning: invalid value encountered in sqrt
  sqrt_data = np.sqrt(data)
